project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - text: "Bridge Longevity Analysis"
        href: Bridge Longevity.qmd
      - text: "Predictive Modeling for Hepatitis C"
        href: Predictive Modeling for Hepatitis C.qmd
      - text: "Movie Recommendation System (KNN)"
        href: Movie Recommendation using KNN.qmd
      - text: "India's Cricket Performance Redesign"
        href: India Performance Redesign.qmd

format:
  html:
    theme: Yeti
    mainfont: poppins
    css: styles.css
    toc: true
    toc-location: left
    number-sections: true
