project:
  type: website
  output-dir: docs

website:
  title: "Harkirat Singh"
  navbar:
    left:
      - NFL Super Bowl Redesign.qmd
      - India Performance Redesign.qmd
      - Codes for NFL Redesign.qmd
      - Codes for Cricket Redesign.qmd
format:
  html:
    theme: Yeti
    mainfont: poppins
    
    css: styles.css
    toc: true




