project:
  type: website
  output-dir: docs

website:
  title: "Harkirat Singh"
  navbar:
    left:
      - RQ1.qmd
      - RQ2.qmd
      - RQ3.qmd
      - Codes for Research Question 1.qmd
      - Codes for Research Question 2.qmd
      - Codes for Research Question 3.qmd
format:
  html:
    theme: Yeti
    mainfont: poppins
    
    css: styles.css
    toc: true




