---
title: "Codes for Research Question 3"
author: 
  - "Harkirat Singh, G01476069"
  - "Shukan Nikikumar Prajapati, G01474606"
  - "DharmpratapSingh ArunodaySingh Vaghela, G01476865"
  - "Group No: 7"
format: 
  html:
    theme: Yeti
    mainfont: poppins
    css: styles.css
    toc: true
---

# Codes

library(tidyverse)    
library(caret)        
library(e1071)        
library(nnet)         
library(pROC)         
library(randomForest) 

data <- read_csv("hcvdat.csv") %>%
  mutate(
    Category = factor(Category, levels = c("0=Blood Donor", "1=Hepatitis", "2=Fibrosis", "3=Cirrhosis"),
                      labels = c("Blood_Donor", "Hepatitis", "Fibrosis", "Cirrhosis")),
    Sex = factor(Sex, levels = c("m", "f")),
    log_ALB = log(ALB + 1),
    log_BIL = log(BIL + 1)
  ) %>%
  na.omit()

set.seed(123)
training_indices <- createDataPartition(data$Category, p = 0.8, list = FALSE)
training_data <- data[training_indices, ]
test_data <- data[-training_indices, ]

fitControl <- trainControl(
  method = "cv",
  number = 10,
  summaryFunction = multiClassSummary,
  classProbs = TRUE,
  savePredictions = "final"
)

model_rf <- train(
  Category ~ log_ALB + log_BIL + AST + ALT + GGT + Sex,
  data = training_data,
  method = "rf",
  trControl = fitControl,
  metric = "Accuracy"
)

model_svm <- train(
  Category ~ log_ALB + log_BIL + AST + ALT + GGT + Sex,
  data = training_data,
  method = "svmRadial",
  trControl = fitControl,
  metric = "Accuracy"
)

predictions_rf <- predict(model_rf, newdata = test_data)
confusionMatrix_rf <- confusionMatrix(predictions_rf, test_data$Category)
probabilities_rf <- predict(model_rf, newdata = test_data, type = "prob")
roc_results_rf <- lapply(levels(test_data$Category), function(class) roc(response = test_data$Category, predictor = probabilities_rf[, class]))
aucs_rf <- sapply(roc_results_rf, auc)

probabilities_svm <- predict(model_svm, newdata = test_data, type = "prob")
roc_results_svm <- lapply(levels(test_data$Category), function(class) roc(response = test_data$Category, predictor = probabilities_svm[, class]))
aucs_svm <- sapply(roc_results_svm, auc)

print(list(RandomForest_AUCs = aucs_rf, SVM_AUCs = aucs_svm))

confusionMatrix_rf <- confusionMatrix(predictions_rf, test_data$Category)
heatmap(as.matrix(confusionMatrix_rf$table), Rowv = NA, Colv = NA, scale = "column", margins = c(5,5), xlab = "Predicted", ylab = "Actual", main = "Confusion Matrix Heatmap")


plot(roc_results_rf[[1]], col="red", main="ROC Curves for Disease Categories")
for (i in 2:length(roc_results_rf)) {
  plot(roc_results_rf[[i]], add = TRUE, col=i)
}
legend("bottomright", legend=levels(test_data$Category), col=1:length(roc_results_rf), lwd=2)

varImpPlot(model_rf$finalModel, main = "Variable Importance in Predicting Liver Disease Severity")
